version: "3.9"

services:
  web:
    build: .
    container_name: home-jawad
    ports:
      - "3001:80"
    depends_on:
      - db
    volumes:
      - ./jawad-website:/var/www/html
    restart: always

  db:
    image: mysql:8.0
    container_name: home-jawad-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: aljawad
      MYSQL_USER: aljawad_user
      MYSQL_PASSWORD: strongpass
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: home-jawad-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    depends_on:
      - db
    restart: always

volumes:
  db_data:

